# Generated by Django 4.1 on 2022-08-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='clasification',
        ),
    ]
