# Generated by Django 4.1 on 2022-08-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_category_producto_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='category',
        ),
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.ManyToManyField(to='producto.category'),
        ),
    ]
