# Generated by Django 3.2 on 2022-08-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_producto_category_producto_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='code',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
    ]
