# Generated by Django 3.2 on 2022-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20220818_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
